/**
 * @Copyright Copyright (C) 2016 General Electric Company. All rights reserved.
 * @author  Ankur Chaudhry
 * @version 1.0
 * @since   2016-07-12
 */

package com.serenity.demo.util;

import org.openqa.selenium.WebDriver;

import net.thucydides.core.guice.Injectors;
import net.thucydides.core.webdriver.WebdriverManager;

public class EY_GettersSetters {

	private static WebDriver driver;

	/**
	**********************************************************************
	* @Function Name : getDriver
	* @Description : Get Driver Instance as generated by the Framework
	* @Param : null
	* @Return : WebDriver
	* @Date : 2016-07-12
	* @Author : Ankur Chaudhry
	***********************************************************************
	*/	  
	public static WebDriver getDriver() {
	    	if(driver==null){
	    		setDriver();
	    	}
	        return driver;
	}

	/**
	**********************************************************************
	* @Function Name : setDriver
	* @Description : Set Driver Instance as generated by the Framework
	* @Param : null
	* @Return : null
	* @Date : 2016-07-12
	* @Author : Ankur Chaudhry
	***********************************************************************
	*/	
	private static void setDriver() {
	    	EY_GettersSetters.driver= Injectors.getInjector().getInstance(WebdriverManager.class).getWebdriver();
	    }

	}

